Feature/star stringtie rnaseq
Ensembl/ensembl-analysis pull request #207
Opened 2021-03-05 10:21 UTC by ens-carlos

# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
New feature
_Include a short description_
New subpipeline config for star stringtie rnaseq
_Include links to JIRA tickets_
https://www.ebi.ac.uk/panda/jira/browse/ENSGENEBUI-485
https://www.ebi.ac.uk/panda/jira/browse/ENSGENEBUI-490
# Testing
_Have you tested it?_
perl -c
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_

2021-03-10 21:13 UTC, thibauthourlier requested changes
Two files should not be in the PR, Genome_anntotation_conf.pm and UniProtCladeDownloadStatic. The changes need to be reverted to their status in feature/breaking_down_1
The copyright value for most of the file is wrong to me, there should be two copyright lines. HiveStar2Introns has the correct values.
It would be great if you can add POD to the methods and check that they are at least correct where the POD is present. I can help you with that if needed.
I feel really bad because I didn't give you the correct information for the pipeline config. I thought the starting branch will only have stringtie and not a mix of everything. I should have checked the non vert pipeline. I will message you to see what is the best way forward.

2021-03-17 20:46 UTC, thibauthourlier commented
I'll probably just use the config later if it's needed for the non vert pipeline. Otherwise it's better to use PR208 to generate the stringtie config

2021-03-19 15:47 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/GenerateGTFLoadingJobs.pm
> +    _branch_to_flow_to => 2,
Applied comment to scallop branch. Could not find this _branch_to_flow_to line.

2021-03-19 15:48 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/GenerateGTFLoadingJobs.pm
> +  #$self->output($output_ids);
Applied comment to scallop branch. Could not find this commented line so it's ok.

2021-03-19 15:50 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveCreateStarJobs.pm
> +use Data::Dumper;
Applied comment to scallop branch. Could not find this line to remove.

2021-03-19 15:50 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveCreateStarJobs.pm
> +  say Dumper($samples_hash);
Applied comment to scallop branch. Could not find this line to remove.

2021-03-19 15:51 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveCreateStarJobs.pm
> +#  my $output_ids = $self->batch_samples($samples_hash);
Applied comment to scallop branch. Could not find this line to remove.

2021-03-19 15:52 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveStar.pm
> - Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Comment applied to scallop branch. Not sure. I think it looks fine in the scallop branch.

2021-03-19 15:53 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveStar.pm
> +    _branch_to_flow_to => 2,
Applied comment to scallop branch. Could not find this line to remove.

2021-03-19 15:54 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveStar.pm
> +  say "Found ".scalar(@$input_ids)." input ids";
Applied comment to scallop branch. All says are say_with_header in scallop branch.

2021-03-19 15:55 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveStar.pm
> + #  $self->throw("DEBUG");
Applied comment to scallop branch. Could not find this line to remove.

2021-03-19 15:56 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/HiveStar2Introns.pm
> +	  %{$self->SUPER::param_defaults},
Applied comment to scallop branch. Alignment is fine in scallop branch.

2021-03-19 16:07 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2.pm
> +
Applied comment to scallop branch. Removed lines.

2021-03-19 16:08 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Runnable/Stringtie2.pm
> +
Comment applied to scallop branch. Already removed.

2021-03-19 16:08 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Runnable/Stringtie2.pm
> +
Comment applied to scallop branch. Already removed.

2021-03-19 16:11 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Runnable/Stringtie2.pm
> +#  my $genome_index  = $self->genome_index;
Comment applied to scallop branch. Removed.

2021-03-19 16:12 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Runnable/Stringtie2.pm
> + # $self->genome_index($genome_index);
Comment applied to scallop branch. Removed.

2021-03-19 16:13 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2Merge.pm
> +  say "Searching for string ".$input_file." in the following csv file:\n".$csv_file;
Comment applied to scallop branch. Removed.

2021-03-19 16:21 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2Merge.pm
> +    say "Checking dir: ".$gtf_dir;
Comment applied to scallop branch. Removed.

2021-03-19 16:24 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2Merge.pm
> +      say "For ".$tissue." only found one file so will just copy it to merged dir";
Comment applied to scallop branch. Replaced.

2021-03-19 16:25 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2.pm
> +  say "Searching for string ".$input_file." in the following csv file:\n".$csv_file;
Comment applied to scallop branch. Replaced.

2021-03-19 16:37 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2.pm
> +  close IN;
Comment applied to scallop branch. Throw if file cannot be closed.

2021-03-19 16:40 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2Merge.pm
> +    close OUT;
Comment applied to scallop branch. Throw if file cannot be closed.

2021-03-19 16:40 UTC, ens-carlos commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/Stringtie2Merge.pm
> +  close IN;
Comment applied to scallop branch. Throw if file cannot be closed.

2021-05-13 09:22 UTC, thibauthourlier commented
I'm closing the PR as it is better to resubmit it when the Star/Scallop config has been verified

2021-05-13 09:22 UTC, closed without merging