added support for sqlalchemy and google authentication
Ensembl/ensembl-analysis pull request #259
Opened 2021-11-23 11:41 UTC by ndliberial

# Requirements
When creating your Pull request, please fill out the template below:

# PR details
_Is this a fix/ update/ new feature?_
Fix
_Include a short description_
Updated db access to use sqlalchemy and added support for google authentication
_Include links to JIRA tickets_

# Testing
_Have you tested it?_
Yes
# Assign to the weekly GitHub reviewer
_If you are a member of Ensembl, please check the Genebuild weekly Rotas and assign this week's GitHub reviewer to the PR_
@thibauthourlier

2021-11-23 16:07 UTC, thibauthourlier requested changes
There are few debugging prints which I haven't flagged but can be removed. Logging with a proper `verbose` flag is totally fine
I'm not sure why the requirements.txt file is mentionned but it probably shouldn't be there as the file in feature/main_alpha has no empty lines
The script seems very similar to https://github.com/Ensembl/ensembl-genes/pull/21. If it does something different, fine, otherwise it feels that it should be in the ensembl-genes repo and be as a library or a script with multiple parameters
It would be nice to have some documentation for the methods/functions

2021-11-24 09:36 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +#from mysql.connector import Error
Done

2021-11-24 09:40 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +  registry_db_url = 'mysql://' + user + ':' + password + '@' + host + ':' + port + '/' + database
Done

2021-11-24 09:40 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
>  #import traceback
Done

2021-11-24 09:40 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +  print(registry_db_url)
Done

2021-11-24 09:48 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +        print(type(e))
Changed to exit function and display the error

2021-11-24 09:49 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +def fetch_db_data1(query,database,host,port,user,password):
Done

2021-11-24 09:55 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +  min_contig_n50_filter = 30000
The reason for the change is to allow us cater for more assemblies outside the 100mb threshold especially now that we are working on some non-verts as well.

2021-11-24 10:00 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +           'https://www.googleapis.com/auth/drive']
Reformatted and parsed as a parameter in subsequent method

2021-11-24 10:00 UTC, ndliberial commented on scripts/genebuild/update_assembly_registry_sheet.py
> +       # gettime = time.time()#Get time of re-authentication
Done

2022-04-05 08:54 UTC, thibauthourlier commented
@williamstark01 git says that there are no new changes since my last review and it looks like git is correct

2022-04-05 09:00 UTC, williamstark01 commented
@thibauthourlier you are right, there are no commits, I saw the resolved comments and mistaken then for code updates in the PR.

@ndliberial are there any updates to push maybe?

2022-05-31 09:23 UTC, williamstark01 commented
@ndliberial are there updates for this PR?

2022-05-31 11:21 UTC, closed without merging