changed name of method to adhere to the documentation of the module
Ensembl/ensembl-analysis pull request #409
Opened 2023-08-02 12:42 UTC by EreboPSilva

# Requirements
When creating your Pull request, please fill out the template below:

# PR details
fix

method name for Slice was old/deprecated?

no JIRA tickets

# Testing
I have tested it on the new enviroment, not in the old one but @swatiebi reports that this was a known fix independently made

# Assign to the weekly GitHub reviewer
@ens-ftricomi @leannehaggerty

2023-08-03 09:19 UTC, ens-ftricomi requested changes
it looks fine to me

2023-08-03 09:19 UTC, ens-ftricomi commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/CleanUTRs.pm
> +	print $self->input_id;
could you print remove the print?

2023-08-08 09:45 UTC, EreboPSilva commented on modules/Bio/EnsEMBL/Analysis/Hive/RunnableDB/CleanUTRs.pm
> +	print $self->input_id;
done!

2023-08-09 08:12 UTC, ens-ftricomi approved these changes
thank you

2023-08-09 08:12 UTC, merged